import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Import opensea Stuff
import * as Web3 from 'web3'
import { OpenSeaPort, Network } from 'opensea-js'

// useEffect stuff 
import { useEffect, useState } from 'react'

// This example provider won't let you make transactions, only read-only calls:
// import opensea stuff
import { EventType } from 'opensea-js'
import * as ActionTypes from './index'
// import { openSeaPort } from '../globalSingletons'






let openseaListen = function (){

}

export default function Home() {
  console.log('home fired')
  const provider = new Web3.providers.HttpProvider('https://mainnet.infura.io/ws/v3/095f60d89db340eea6a82a00a804584d')

  const seaport = new OpenSeaPort(provider, {
    networkName: Network.Main,
    apiKey: ''
  }, (logs) => {
    console.log('logs: ',{logs})
  })

  const [data, setData] = useState(null)
  // const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    console.log('useEffect fired')
    setData('data set in useEffect')

    seaport.api.getOrders({ limit: 50 }).then(orders => {
      console.log({ orders })
    })
    
    seaport.addListener(EventType.TransactionCreated, ({ transactionHash, event }) => {
      console.log("tx hash>>", { transactionHash, event })
      setData(transactionHash)
      // dispatch({ type: ActionTypes.SET_PENDING_TRANSACTION_HASH, hash: transactionHash })
    })

    
    // setLoading(true)
    // fetch('api/profile-data')
    //   .then((res) => res.json())
    //   .then((data) => {
    //     setData(data)
    //     setLoading(false)
    //   })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button onClick={openseaListen}>
          call function openseaListen
        </button>
        <h1>data:</h1>
        <p>{data}</p>


        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
